### ISSUE TITLE
When will the code be released

### ISSUE THREAD

**Issue by l11x0m7** [thu-coai/ConPer#1]
Hello

恭喜中了NAACL，请问代码何时可以公开呢？

**Comment by nonstopfor** [comment]
大概6月份

**Comment by l11x0m7** [comment]
好的

**Comment by Jiaxin-Wen** [comment]
Sorry for the delay. We've really been a bit out-of-bandwidth these days 😄
We have released our data, code, and fine-tuned checkpoint.
