### ISSUE TITLE
When will the code be released? 

### ISSUE THREAD

**Issue by Dinxin** [thu-coai/ConPer#2]
Hello, it's my honor to read your NAACL 2022 paper with respect to persona-based story generation. The paper claims that the code is available, but I had not found it in this repo by the end of June 2022. Therefore, I still want to ask the question: when will the code be released, although there was a developer who asked the same question in another issue which is closed now.

**Comment by Dinxin** [comment]
It is now August 2022. What is your exact schedule for open-sourcing the code as you promised in your NAACL 2022 paper?

**Comment by Jiaxin-Wen** [comment]
Sorry for the delay. We've really been a bit out-of-bandwidth these days 😄 
We have released our data, code, and fine-tuned checkpoint.
